### ISSUE TITLE
intesishome with PA-AW-WIFI-1 on Aquarea AW

### ISSUE THREAD

**Issue by jeo25550** [jnimmo/hass-intesishome#2]
hello,
I test this integration on homeassistant but have this fail log:

Cant you help me please.

2022-09-18 19:12:06.847 ERROR (MainThread) [homeassistant.components.climate] Error while setting up intesishome platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/intesishome/climate.py", line 128, in async_setup_platform
    [
  File "/usr/src/homeassistant/homeassistant/components/intesishome/climate.py", line 129, in <listcomp>
    IntesisAC(ih_device_id, device, controller)
  File "/usr/src/homeassistant/homeassistant/components/intesishome/climate.py", line 203, in __init__
    mode_list = [MAP_IH_TO_HVAC_MODE[mode] for mode in modes]
  File "/usr/src/homeassistant/homeassistant/components/intesishome/climate.py", line 203, in <listcomp>
    mode_list = [MAP_IH_TO_HVAC_MODE[mode] for mode in modes]
KeyError: 'heat+tank'

**Comment by jnimmo** [comment]
Hi there, it looks like the integration is having difficulty mapping "heat+tank" mode to Home Assistant's HVAC modes (heat/cool/dry/fan/auto/off).
I've just spent a couple of hours splitting out the tank setting into the preset mode in Home Assistant, as Home Assistant doesn't support adding custom HVAC modes. Hopefully this will offer a solution for you.

You can test this out by replacing your current version of hass-intesishome/climate.py with this one https://github.com/jnimmo/hass-intesishome/blob/aquarea-tank-presets/custom_components/intesishome/climate.py
then restarting Home Assistant.

Please update your configuration.yaml file to include the following while testing in case you run into any errors and need to provide some debug logs
```
logger:
  default: info
  logs:
    pyintesishome: debug
    homeassistant.components.intesishome: debug
```

**Comment by ghost** [comment]
Hi,
thank you for your answer, I modified climate.py like this because the Fan mode does not exist on Aquarea PANASONIC:

MAP_IH_TO_HVAC_MODE = {
    "auto": HVACMode.HEAT_COOL,
    "cool": HVACMode.COOL,
    "dry": HVACMode.DRY,
    "fan": HVACMode.FAN_ONLY,
    "heat": HVACMode.HEAT,
    "heat+tank":HVACMode.HEAT,
    "tank":HVACMode.HEAT,
    "cool+tank":HVACMode.COOL,
    "auto+tank":HVACMode.HEAT_COOL,
    "off": HVACMode.OFF,
}

The module starts now but very little data goes up on the page.
Is there a solution to bring up all the data visible in the log?

[json.txt](https://github.com/jnimmo/hass-intesishome/files/9784500/json.txt)

I identified some UID in this file
[UID Aquarea.xlsx](https://github.com/jnimmo/hass-intesishome/files/9784555/UID.Aquarea.xlsx)

maybe this will help you. 
best regard

**Comment by jnimmo** [comment]
It looks like I started some work on this at https://github.com/jnimmo/hass-intesishome/tree/aquarea-tank-presets but didn't complete. Closing due to the age of this issue but happy for it to be re-opened if someone else is happy to test out and debug the changes.

**Comment by ghost** [comment]
Hello, I will happy to test if you make some modifications !

De : James Nimmo ***@***.***>
Envoyé : mardi 17 décembre 2024 08:00
À : jnimmo/hass-intesishome ***@***.***>
Cc : RENAUD Georges ***@***.***>; Comment ***@***.***>
Objet : Re: [jnimmo/hass-intesishome] intesishome with PA-AW-WIFI-1 on Aquarea AW (Issue #2)


It looks like I started some work on this at https://github.com/jnimmo/hass-intesishome/tree/aquarea-tank-presets but didn't complete. Closing due to the age of this issue but happy for it to be re-opened if someone else is happy to test out and debug the changes.

-
